export const SRS_OFFSETS = [1, 4, 7, 14, 28, 40];

export const NEET_DATE = import.meta.env.VITE_NEET_DATE || '2026-05-03T09:00:00+05:30';

export const BRUTAL_MOTIVATIONS = [
  "No excuses. Open the book.",
  "Less scrolling, more studying.",
  "Hard now, easy exams later.",
  "Win the study hour.",
  "Be undeniable in your results.",
  "Your future self is watching.",
  "Excellence is a daily habit.",
  "Discomfort now, freedom later.",
  "Champions revise when they don’t feel like it.",
  "Success is earned in silence.",
  "Discipline beats motivation.",
  "One more page, no matter what.",
  "Suffer through the boring chapters.",
  "Comfort is the enemy of grades.",
  "Consistency creates mastery.",
  "Excuses don’t write essays.",
  "Nobody cares, study harder.",
  "Be relentless with revision.",
  "Work until answers flow naturally.",
  "Sacrifice distraction or stay the same.",
  "Earn your rest by studying first.",
  "Get sharper or get left behind.",
  "Outwork your past self.",
  "Grind now, brag later.",
  "Mental pain builds intellectual strength.",
  "Your competition is revising.",
  "Excuses are for the weak-minded.",
  "Focus is your weapon.",
  "Be the hardest worker in the library.",
  "Your feelings don’t matter to deadlines.",
  "Every page counts.",
  "Don’t stop until you’re proud.",
  "Comfort kills progress.",
  "Push limits or stay average.",
  "Quit complaining, start reading.",
  "Weakness leaves when effort enters.",
  "Get comfortable being uncomfortable.",
  "Masters are built, not born.",
  "Dominate your study session.",
  "Outlearn everyone.",
  "Results demand sacrifice.",
  "Hustle in silence.",
  "Struggle makes scholars.",
  "Stop wishing, start working.",
  "The grind knows no excuses.",
  "Discomfort is growth.",
  "Outlast the mental fatigue.",
  "One day or day one. You choose.",
  "Study now, shine forever.",
  "Excuses are lies.",
  "Dreams demand discipline.",
  "If you’re tired, revise tired.",
  "Champions don’t quit revising.",
  "Grind until they can’t ignore your grades.",
  "Effort is free.",
  "Sacrifice comfort for mastery.",
  "Earn every grade.",
  "Push past your mental limits.",
  "Focus harder.",
  "Your brain won’t quit. Your will does.",
  "Dominate the moment.",
  "Show up every day.",
  "The pain is the point.",
  "Grind, learn, repeat.",
  "Excuses change nothing.",
  "Hard work beats talent.",
  "Do it now or regret later.",
  "Study is success in progress.",
  "Be stronger than your excuses.",
  "Stop stopping.",
  "Work until your idols are rivals.",
  "Don’t wait. Revise.",
  "Excuses don’t pass exams.",
  "Stay hungry, stay ruthless.",
  "Winners don’t skip study sessions.",
  "Sacrifice today, dominate tomorrow.",
  "Your grind defines your grades.",
  "No pain, no progress.",
  "Study insane or remain the same.",
  "Be addicted to improvement.",
  "Mental pain is growth.",
  "Effort never lies.",
  "Weakness isn’t welcome here.",
  "Do it for future you.",
  "One page at a time.",
  "The grind is the reward.",
  "Shut up and study.",
  "Success is hidden in late nights.",
  "Rise and grind.",
  "Sacrifice equals success.",
  "Outwork yesterday’s version of you.",
  "Excuses are useless.",
  "Push or be pushed aside.",
  "Commit or quit.",
  "Work beats whining.",
  "Results require suffering.",
  "Prove them wrong with grades.",
  "Grind without mercy.",
  "Discipline equals freedom.",
  "Every day counts.",
  "Failure is fuel.",
  "No retreat, no surrender.",
  "Make boredom your ally.",
  "Do the work.",
  "Sacrifice beats shortcuts.",
  "Effort over excuses.",
  "Build knowledge, don’t beg for it.",
  "No one cares. Work harder.",
  "Wisdom is earned.",
  "Outwork the doubt.",
  "Consistency wins exams.",
  "Fatigue reveals strength.",
  "Work now, shine later.",
  "Do hard readings.",
  "Results require repetition.",
  "Grind with purpose.",
  "The desk is the battlefield.",
  "Don’t skip the struggle.",
  "Pay your dues in focus.",
  "Sacrifice is strength.",
  "Push until you learn.",
  "Excuses are for losers.",
  "Be obsessed or be average.",
  "Earn respect with results.",
  "Dominate distractions.",
  "Knowledge comes from struggle.",
  "Grind in silence.",
  "Excuses won’t answer the test.",
  "Stop talking, start reading.",
  "Every day is exam prep.",
  "Work beats talent.",
  "Excuses won’t transform you.",
  "Make discipline your superpower.",
  "Hustle until you’re remembered.",
  "Excuses change nothing.",
  "Push the brain barrier.",
  "Be addicted to the grind.",
  "The exam doesn’t care.",
  "Sacrifice sleep if you must.",
  "Hard work is undefeated.",
  "Stay ruthless.",
  "Results demand resilience.",
  "No one owes you a pass.",
  "The grind tests your character.",
  "Suffer with purpose.",
  "Excuses destroy progress.",
  "Push when it’s boring.",
  "Your grind, your glory.",
  "No grind, no greatness.",
  "Don’t cheat the grind.",
  "Excuses are wasted energy.",
  "Work until you know it.",
  "Discipline is destiny.",
  "Fight for every answer.",
  "Focus is sacrifice.",
  "Grind harder than yesterday.",
  "Quitters don’t graduate.",
  "Excuses build nothing.",
  "Pain is proof of effort.",
  "Respect the grind.",
  "Excuses make you weak.",
  "Dominate or disappear.",
  "Your grind is your weapon.",
  "Sacrifice excuses.",
  "Stay on the grind.",
  "Hard work creates masters.",
  "Excuses won’t save you.",
  "Grind through the boredom.",
  "Discipline never fails.",
  "Sacrifice mediocrity.",
  "Every page is progress.",
  "Excuses kill dreams.",
  "Effort earns results.",
  "Focus builds strength.",
  "Work until it hurts.",
  "Grind over comfort.",
  "Excuses are poison.",
  "Hustle until you drop.",
  "Sacrifice is the shortcut.",
  "Every second counts.",
  "Grind until you break limits.",
  "Excuses delay greatness.",
  "No study, no success.",
  "Excuses won’t get results.",
  "Work through the fatigue.",
  "Sacrifice excuses for excellence.",
  "The grind builds greatness.",
  "Excuses equal weakness.",
  "Push past excuses.",
  "Excuses steal progress.",
  "Grind is forever.",
  "Be ruthless with excuses.",
  "Effort or nothing.",
  "Excuses won’t change grades.",
  "Sacrifice your comfort zone.",
  "Grind makes scholars.",
  "Excuses never win.",
  "Struggle proves persistence.",
  "Grind creates growth.",
  "Excuses bury ambition.",
  "Grind past limits.",
  "Sacrifice excuses daily.",
  "Excuses break discipline.",
  "Knowledge is victory.",
  "Excuses waste time.",
  "Sacrifice makes champions.",
  "Excuses are weakness in disguise.",
  "Grind like it’s your last chance.",
  "No excuses, just results.",
  "Sacrifice excuses for progress.",
  "Grind demands sacrifice.",
  "Excuses sabotage strength.",
  "Hard work wins exams.",
  "Excuses won’t move you forward.",
  "Grind is everything.",
  "Sacrifice builds legacy.",
  "Excuses lose battles.",
  "Push past weakness.",
  "Excuses fade, results stay.",
  "Effort never lies.",
  "Grind breaks excuses.",
  "Sacrifice excuses for focus.",
  "Excuses are comfort.",
  "Grind destroys comfort.",
  "Sacrifice excuses for growth.",
  "Excuses erase progress.",
  "No grind, no glory.",
  "Excuses weaken minds.",
  "Sacrifice your limits.",
  "Grind cures excuses.",
  "Excuses break progress.",
  "Study or surrender.",
  "Grind kills weakness.",
  "Sacrifice mediocrity daily.",
  "Excuses slow success.",
  "Boredom is progress.",
  "Grind crushes excuses.",
  "Sacrifice excuses relentlessly.",
  "Excuses are for tomorrow.",
  "Grind today, shine tomorrow.",
  "Sacrifice excuses to win.",
  "Excuses don’t define you.",
  "Grind reveals greatness.",
  "Sacrifice excuses brutally.",
  "Excuses weaken discipline.",
  "Grind destroys doubt.",
  "Sacrifice or stay weak.",
  "Excuses delay destiny.",
  "Focus is the truth.",
  "Grind fuels greatness.",
  "Sacrifice excuses consistently.",
  "Excuses stop growth.",
  "Grind turns pain to power.",
  "Sacrifice excuses ruthlessly.",
  "Excuses breed failure.",
  "Grind until you conquer.",
  "Sacrifice excuses permanently.",
  "Excuses block progress.",
  "Grind or give up.",
  "Sacrifice excuses forever.",
  "Excuses weaken the strong.",
  "Grind exposes excuses.",
  "Sacrifice excuses endlessly.",
  "Excuses make you ordinary.",
  "Grind turns effort to excellence.",
  "Sacrifice excuses without mercy.",
  "Excuses never built scholars.",
  "Grind harder, excuses die.",
  "Sacrifice excuses entirely.",
  "Excuses can’t pass exams.",
  "Grind shapes destiny.",
  "Sacrifice excuses always.",
  "Excuses feed weakness.",
  "Grind sharpens discipline.",
  "Sacrifice excuses at all costs.",
  "Excuses keep you soft.",
  "Grind until excuses vanish.",
  "Sacrifice excuses first.",
  "Excuses protect mediocrity.",
  "Grind builds minds.",
  "Sacrifice excuses mercilessly.",
  "Excuses starve success.",
  "Grind for greatness.",
  "Sacrifice excuses daily and nightly.",
  "Excuses fuel failure.",
  "Grind beyond limits.",
  "Sacrifice excuses endlessly.",
  "Excuses betray effort.",
  "Grind endlessly.",
  "Sacrifice excuses immediately.",
  "Excuses ruin results.",
  "Grind breaks boundaries.",
  "Sacrifice excuses constantly.",
  "Excuses destroy focus.",
  "Grind wins always.",
  "Sacrifice excuses continuously.",
  "Excuses end dreams.",
  "Grind doesn’t quit.",
  "Sacrifice excuses completely.",
  "Excuses stop warriors.",
  "Grind conquers excuses.",
  "Sacrifice excuses ruthlessly.",
  "Excuses fear effort.",
  "Grind builds kings.",
  "Sacrifice excuses automatically.",
  "Excuses paralyze progress.",
  "Grind or die trying.",
  "Sacrifice excuses systematically.",
  "Excuses lose the game.",
  "Grind burns excuses.",
  "Sacrifice excuses absolutely.",
  "Excuses belong to the weak.",
  "Grind defines greatness.",
  "Sacrifice excuses without hesitation.",
  "Excuses waste potential.",
  "Grind relentlessly.",
  "Sacrifice excuses permanently."
];

export const SUBJECT_COLORS = {
  Physics: 'red',
  Chemistry: 'orange',
  Biology: 'green'
} as const;